version: '3.8'

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
  database:
    container_name: database
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: weddingplannerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123qwe
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/Wedding_Planner
      - php-var:/var/www/Wedding_Planner/var
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/Wedding_Planner
      - php-var:/var/www/Wedding_Planner/var
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  php-var:
